config/routes.rb
CoopSite::Application.routes.draw do

  root 'coops#index'

  get "/auth/google_login/callback" => "sessions#create"
  get "/signout" => "sessions#destroy", :as => :signout

  resources :coops do
    resources :meals do
      collection do
        get "edit_mult"
        put "update_mult"
      end
    end

    resources :shifts do
      collection do
        get "edit_mult"
        put "update_mult"
      end

      member do
        get "add_user"
        get "remove_user"
        get "add_user_pic/:pic", action: 'add_user_pic', as: 'add_user_pic'
      end

      resources :swap_requests do
        member do
          get "resolve"
        end
      end
    end

    member do
      get 'generate_member_join_link'
      get 'generate_admin_join_link'
      get 'member_join_link/:member_join_hash', action: 'member_join'
      get 'admin_join_link/:admin_join_hash', action: 'admin_join'
    end
  end

  resources :users do
    get 'edit_shifts'
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  include ActionView::Helpers::NumberHelper

  belongs_to :coop
  has_many :swap_requests
  has_and_belongs_to_many :shifts
  validates_uniqueness_of :email

  after_create :send_account_create_email
  before_save :clean_phone

  def allowed_phone
    ap = nil
    if self.phone && self.display_phone
      ap = self.phone_pretty
    end
    ap
  end

  def allowed_email
    ae = nil
    if self.email && self.display_email
      ae = self.email
    end
    ae
  end

  def phone_pretty
    number_to_phone(self.phone, area_code: true)
  end

  def send_account_create_email
    UserMailer.welcome_email(self).deliver
  end

  private
    def clean_phone
      if self.phone
        self.phone.gsub!(/[^0-9]/, '')
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :set_coop, only: [:show, :edit]
  before_action :is_same_user, only: [:edit, :update, :show]
  before_action :is_admin, only: [:destroy]

  def home
    unless current_user
      render action: 'index'
    else
      redirect_to coop_path(current_user.coop_id)
    end
  end

  # GET /users
  # GET /users.json
  def index
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @selected = 'shifts'
    @swap_requests = @coop.swap_requests
  end

  def edit_shifts
    @selected = 'shifts'
    @user = User.find(params[:user_id])
    is_same_user
    @coop = @user.coop
    @days = normal_week_lowercase;
    @breakfasts = {}
    @lunches = {}
    @dinners = {}
    @others = {}
    @days.each do |day|
      @breakfasts[day] = []
      @lunches[day] = []
      @dinners[day] = []
      @others[day] = []
      shifts = Shift.where(coop: @coop, day: day)
      shifts.each do |shift|
        if shift.meals && shift.meals.first
          meal_type = shift.meals.first.meal_type
          if meal_type == 'breakfast'
            @breakfasts[day] << shift
          elsif meal_type == 'lunch'
            @lunches[day] << shift
          elsif meal_type == 'dinner'
            @dinners[day] << shift
          else
            @others[day] << shift
          end
        else
          @others[day] << shift
        end
      end
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @selected = 'edit_user'
    @hide_nav_links = (@user.username == nil || @user.username == '')
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to signout_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coop
      @coop = @user.coop
    end

    def set_user
      @user = User.find(params[:id])
    end

    def is_same_user
      unless @user.id == current_user.id
        redirect_to root_path, notice: 'Cannot edit other users'
      end
    end

    def is_admin
      unless current_user.admin?
        redirect_to root_path, notice: 'Must be admin to do that!'
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :username, :phone, :display_email, :display_phone, :pic)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="coop">
    Member of <%= @coop.name %>
  </div>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username, required: 'required' %>
  </div>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email, readonly: 'readonly' %>
  </div>

  <div class="field">
    <%= f.label :display_email %><br>
    <%= f.check_box :display_email %>
  </div>

  <div class="phone">
    <%= f.label :phone %><br>
    <%= f.phone_field :phone %>
  </div>

  <div class="field">
    <%= f.label :display_phone %><br>
    <%= f.check_box :display_phone %>
  </div>

  <div class="field">
    <%= f.label "I'm Head Cook/PIC trained" %><br>
    <%= f.check_box :pic %>
  </div>

  <div class="actions">
    <%= f.submit 'Save' %>
  </div>
<% end %>

app/views/users/_my_shifts.html.erb
<div class='my_shifts'>
  <% @user.shifts.each do |shift| %>
    <div class='shift'>
      <div class='shift_header'>
      <div class='left_content'>
        <span class='name'><%= shift.niceTitle %></span>
        </div>
        <div class='right_content'>
        <%= link_to 'remove from my shifts', remove_user_coop_shift_path(@coop, shift), class: 'shift_link remove_shift_link' %>
        <span class='divider'>|</span>
        <%= link_to 'swap', new_coop_shift_swap_request_path(@coop, shift), class: 'shift_link swap_shift_link' %>
        </div>
      </div>
      <div class='shift_info'>
          <% if shift.pic %>
            <div class='leader'>
              <span class='detail_left'>PIC:</span>
              <span class='detail_right'><%= render 'users/user_in_shift', user: shift.pic %></span>
            </div>

          <% elsif shift.headCook %>
            <div class='leader'>
              <span class='detail_left'>Head Cook:</span>
              <span class='detail_right'><%= render 'users/user_in_shift', user: shift.headCook %></span>
            </div>
          <% end %>

          <% first = true %>
          <% shift.users.each do |user| %>
            <% if user == shift.pic || user == shift.headCook %>
              <% next %>
            <% end %>
            <% if first %>
              <div class='member'>
              <span class='detail_left'>Everyone else:</span>
              <span class='detail_right'><%= render 'users/user_in_shift', user: user %></span>
              <% first = false %>
              </div>
            <% else %>
              <div class='member'>
                <span class='detail_right'><%= render 'users/user_in_shift', user: user %></span>
              </div>
            <% end %>
          <% end %>
      </div>
    </div>
  <% end %>
  <div class='shift_add'>
  <%= link_to '+ Add new shifts', user_edit_shifts_path(@user), class: 'shift_add_link' %>
  </div>
</div>

app/views/users/_swap_requests.html.erb
<div class='swap_requests'>
  <% @swap_requests.each do |swap_request| %>
    <% unless swap_request.isResolved? %>
      <div class='swap_request'>

        <div class='top_content'>
          <% if swap_request.user.username %>
            <span class='user_name'>
              <%= swap_request.user.username %>
            </span>
          <% end -%>
          <span class='swap_shift_info'>
            <%= swap_request.shift.niceTitle %>
            (<%= swap_request.date.strftime('%B %-d') %>)
          </span>
        </div>

        <div class='bottom_content'>
          <% if swap_request.headcook_required %>
            <div class='note'>Head cook or PIC required</div>
          <% end %>
          <% if swap_request.message %>
            <div class='message'>
              <%= swap_request.message %>
            </div>
          <% end %>
          <div class='contact_info'>
            <% if swap_request.user.allowed_email %>
              <span class='email'>
                <%= swap_request.user.email %>
              </span>
            <% end %>
            <% if swap_request.user.allowed_phone %>
              <span class='phone'>
                <%= swap_request.user.phone_pretty %>
              </span>
            <% end %>
          </div>
          <% if swap_request.user == current_user %>
            <div class='swap_request_links'>
              <%= link_to 'Remove request', resolve_coop_shift_swap_request_path(@coop, swap_request.shift, swap_request), id: 'resolve_swap_request' %>
              <%= link_to 'Edit', edit_coop_shift_swap_request_path(@coop, swap_request.shift, swap_request), id: 'edit_swap_request' %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/users/_user_in_shift.html.erb
<% if user == current_user %>
  <span class='username'><%= user.username %> (you)</span>
<% else %>
  <span class='username'><%= user.username %></span>
<% end %>

<span class='email'><%= user.allowed_email %></span>

<span class='phone'><%= user.allowed_phone %></span>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<div class='account_destroy'>
  <span class='info'>No longer in <%= @user.coop.name %>?</span>
  <%= link_to 'Delete your account', @user, method: :delete %>
</div>

<%= link_to 'Back to shifts', @user %>

app/views/users/edit_shifts.html.erb
<div id='shift_select_page'>
<h2>Select your <%= @coop.name %> shifts:</h2>

<table>
  <tr>
    <th class='shifts_row_label'></th>
    <% @days.each do |day| %>
      <th><%= day.capitalize %></th>
    <% end %>
  </tr>
  <tr>
    <td class='shifts_row_label breakfast'>Breakfast:</td>
    <% @days.each do |day| %>
      <td>
        <% @breakfasts[day].each do |shift| %>
          <% @shift = shift %>
          <div class='shift_toggle'>
            <%= render 'shifts/add_remove_show' %>
          </div>
        <% end %>
      </td>
    <% end %>
  </tr>
  <tr>
    <td class='shifts_row_label lunch'>Lunch:</td>
    <% @days.each do |day| %>
      <td>
        <% @lunches[day].each do |shift| %>
          <% @shift = shift %>
          <div class='shift_toggle'>
            <%= render 'shifts/add_remove_show' %>
          </div>
        <% end %>
      </td>
    <% end %>
  </tr>
  <tr>
    <td class='shifts_row_label dinner'>Dinner:</td>
    <% @days.each do |day| %>
      <td>
        <% @dinners[day].each do |shift| %>
          <% @shift = shift %>
          <div class='shift_toggle'>
            <%= render 'shifts/add_remove_show' %>
          </div>
        <% end %>
      </td>
    <% end %>
  </tr>
  <tr>
    <td class='shifts_row_label other'>Other:</td>
    <% @days.each do |day| %>
      <td>
        <% @others[day].each do |shift| %>
          <% @shift = shift %>
          <div class='shift_toggle'>
            <%= render 'shifts/add_remove_show' %>
          </div>
        <% end %>
      </td>
    <% end %>
  </tr>
</table>

<%= link_to 'Done Editing', user_path(@user), class: 'done_link' %>

</div>

<div id='alert_area'></div>

app/views/users/index.html.erb
<h1>Welcome to Co-op site thing</h1>

<p id="notice"><%= notice %></p>

<% if current_user %>
  <p>Welcome <%= current_user.email %></p>
  <%= link_to 'Sign out', signout_path %>
<% else %>
  <p><%= link_to 'Sign in!', "/auth/google_login" %></p>
<% end %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div class='shift_area'>
  <h2>Your <%= @coop.name %> shifts:</h2>
  <%= render 'my_shifts' %>

  <div id='swap_form_holder'></div>
</div>

<div class='swap_area'>
  <h2>Swapportunities</h2>
  <%= render 'swap_requests' %>
</div>