config/routes.rb
CoopSite::Application.routes.draw do

  root 'coops#index'

  get "/auth/google_login/callback" => "sessions#create"
  get "/signout" => "sessions#destroy", :as => :signout

  resources :coops do
    resources :meals do
      collection do
        get "edit_mult"
        put "update_mult"
      end
    end

    resources :shifts do
      collection do
        get "edit_mult"
        put "update_mult"
      end

      member do
        get "add_user"
        get "remove_user"
        get "add_user_pic/:pic", action: 'add_user_pic', as: 'add_user_pic'
      end

      resources :swap_requests do
        member do
          get "resolve"
        end
      end
    end

    member do
      get 'generate_member_join_link'
      get 'generate_admin_join_link'
      get 'member_join_link/:member_join_hash', action: 'member_join'
      get 'admin_join_link/:admin_join_hash', action: 'admin_join'
    end
  end

  resources :users do
    get 'edit_shifts'
  end

end

app/models/shift.rb
class Shift < ActiveRecord::Base
  belongs_to :coop
  has_and_belongs_to_many :users
  has_and_belongs_to_many :meals
  has_many :swap_requests

  def isLeader
  end

  def isLeader=(checkbox)
  end

  def headCook
    hc = nil
    if self.leader && (self.activity == 'cook_1' || self.activity == 'cook_2' || self.activity == 'cook')
      hc = User.find(self.leader)
    end
    hc
  end

  def pic
    pic = nil
    if self.leader && !self.headCook
      pic = User.find(self.leader)
    end
    pic
  end

  def niceTitle
    activities = {'kp' => 'Kitchen Prep', 'cook_1' => '1st Hour Cook', 'cook_2' => '2nd Hour Cook', 'pre_crew' => 'Pre-Crew', 'crew' => 'Crew'}
    title = self.day.capitalize
    if self.meals && self.meals.first
      title << ' ' + self.meals.first.meal_type.capitalize
    end
    title << ' ' + (activities[self.activity] ? activities[self.activity] : self.activity.capitalize)
    title
  end

  def pretty_activity
    activities = {'kp' => 'Kitchen Prep', 'cook_1' => '1st Hour Cook', 'cook_2' => '2nd Hour Cook', 'pre_crew' => 'Pre-Crew', 'crew' => 'Crew'}
    activities[self.activity] ? activities[self.activity] : self.activity.capitalize
  end

  def self.delete_all(activity, coop)
    Shift.where(coop: coop, activity: activity).each do |shift|
      shift.destroy
    end
  end

  # The day of the week this shift occurs on, as an integer
  def dayNum
    ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'].index(self.day.downcase)
  end

  # Return an array of ["MonthName dayNum", ...] for all days on which
  # this shift could occur to populate the shift swap form
  def allFutureDates
    curday = Date.today
    end_of_fall = Date.new(Date.today.year, 12, 31)
    end_of_spring = Date.new(Date.today.year, 5, 30)
    curday < end_of_spring ? end_date = end_of_spring : end_date = end_of_fall
    dayNum = self.dayNum
    dates = []

    while curday <= end_date
      if curday.wday == dayNum
        dates.append(Date::MONTHNAMES[curday.month] + " #{curday.day}")
      end
      curday = curday.next_day
    end

    dates
  end

  def self.make_shifts(activity, shift_params, coop)
    days = ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday']
    days.each do |day|
      old_shift = Shift.where(coop: coop, activity: activity, day: day).first
      if shift_params[day + '_' + activity]
        if activity == 'other_shift'
          new_shift = Shift.create(day: day, coop: coop, activity: shift_params[:other_shift_name], start_time: shift_params[:time])
        else
          new_shift = Shift.create(day: day, coop: coop, activity: activity, start_time: shift_params[:time])
        end
        if old_shift
          new_shift.users = old_shift.users
        end
      end
      if old_shift
        old_shift.swap_requests.each do |sr|
          sr.destroy
        end
        old_shift.destroy
      end
    end
  end

  def self.makeForMealsOnDay(daynum, meals, params, coop, old_shifts)
    meal = meals.first.meal_type
    days = ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday']
    day = days[daynum]
    activities = {}
    params.each_key do |key|
      if key.include? "_#{meal}"
        act = key.gsub("_#{meal}", "")
        unless days.include? act
          activities[act] = 'exists'
        end
      end
    end

    new_shifts = []
    destroy_shifts = []
    if (old_shifts)
      old_shifts.each do |shift|
        if activities[shift.activity] == 'exists'
          new_shifts << shift
          activities[shift.activity] = 'found'
        else
          destroy_shifts << shift
        end
      end
    end

    destroy_shifts.each do |shift|
      shift.swap_requests.each do |sr|
        sr.destroy
      end
      shift.destroy
    end

    new_shifts.each do |shift|
      shift.meals = meals
    end

    out = []
    activities.each_pair do |activity, found|
      out << activity
      unless found == 'found'
        shift = Shift.create(day: day, coop: coop, activity: activity)
        out << shift
        shift.meals = meals
      end
    end
    puts out.inspect
  end
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  before_action :set_shift, only: [:show, :edit, :update, :destroy, :add_user, :remove_user, :add_user_pic]
  before_action :set_coop, only: [:add_user, :remove_user, :add_user_pic]

  # adds the current user to this shift
  def add_user
    @user = current_user
    if @user.pic
      puts @shift.inspect
      render partial: 'shift_pic_confirm_deny'
    else
      unless @shift.users.include?(@user)
        @shift.users << @user
        render partial: 'add_remove_show', shift: @shift, notice: 'Successfully joined shift.'
      else
        render partial: 'add_remove_show', shift: @shift, notice: 'You\'re already on this shift.'
      end
    end
  end

  def add_user_pic
    @user = current_user
    unless @shift.users.include?(@user)
      if params[:pic] == 'true'
        @shift.leader = @user.id
        @shift.save
        @shift.meals.each do |meal|
          meal.head_cook = @user.id
          meal.save
        end
      end
      @shift.users << @user

      render partial: 'add_remove_show', shift: @shift, notice: 'Successfully joined shift.'
    else
      render partial: 'add_remove_show', shift: @shift, notice: 'You\'re already on this shift.'
    end
  end

  # remove the current user from this shift
  def remove_user
    @user = current_user
    if @shift.users.include?(@user)
      @shift.users.delete(@user)
      # make sure we're no longer the leader
      if @shift.leader == @user.id
        @shift.leader = nil
        if @shift.save
          @shift.meals.each do |meal|
            meal.head_cook = nil
            meal.save
          end
          render partial: 'add_remove_show', shift: @shift, notice: 'Successfully removed from shift.'
        else
          render partial: 'add_remove_show', shift: @shift, notice: "Couldn't remove you"
        end
      else
        render partial: 'add_remove_show', shift: @shift, notice: "Successfully removed from shift."
      end
    else
      render partial: 'add_remove_show', shift: @shift, notice: "You were never on this shift."
    end
  end

  # GET /shifts
  # GET /shifts.json
  def index
    @shifts = Shift.all
  end

  # GET /shifts/1
  # GET /shifts/1.json
  def show
  end

  # GET /shifts/new
  def new
    @shift = Shift.new
  end

  # GET /shifts/1/edit
  def edit
  end

  # POST /shifts
  # POST /shifts.json
  def create
    @shift = Shift.new(shift_params)
    # Set user, coop, leader
    @shift.users << current_user
    @shift.coop_id = current_user.coop_id
    if shift_params[:isLeader] == "yes"
      @shift.leader = current_user.id
    else
      @shift.leader = nil
    end

    respond_to do |format|
      if @shift.save
        format.html { redirect_to @shift, notice: 'Shift was successfully created.' }
        format.json { render action: 'show', status: :created, location: @shift }
      else
        format.html { render action: 'new' }
        format.json { render json: @shift.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shifts/1
  # PATCH/PUT /shifts/1.json
  def update
    # Set the shift's leader
    if shift_params[:isLeader] == "yes"
      @shift.leader = current_user.id
    else
      @shift.leader = nil
    end

    respond_to do |format|
      if @shift.update(shift_params)
        format.html { redirect_to @shift, notice: 'Shift was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @shift.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shifts/1
  # DELETE /shifts/1.json
  def destroy
    @shift.destroy
    respond_to do |format|
      format.html { redirect_to shifts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shift
      @shift = Shift.find(params[:id])
    end

    def set_coop
      @coop = Coop.find(params[:coop_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shift_params
      params.require(:shift).permit(:coop_id, :day, :start_time, :end_time, :activity, :isLeader)
    end
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/views/shifts/_add_remove_show.html.erb
<% if @shift.users.include? @user %>
  <%= link_to @shift.pretty_activity, remove_user_coop_shift_path(@coop, @shift), class: 'remove_shift add_remove_link' %>
<% else %>
  <%= link_to @shift.pretty_activity, add_user_coop_shift_path(@coop, @shift), class: 'add_shift add_remove_link' %>
<% end %>

app/views/shifts/_form.html.erb
<%= form_for(@shift) do |f| %>
  <% if @shift.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shift.errors.count, "error") %> prohibited this shift from being saved:</h2>

      <ul>
      <% @shift.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :day %><br>
    <%= f.select :day, Date::DAYNAMES.zip(Date::DAYNAMES)%>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.time_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.time_select :end_time %>
  </div>
  <div class="field">
    <%= f.label :activity %><br>
    <%# f.text_field :activity %>
    <%= f.select :activity, [['Cooking', 'Cooking'], ['Crew', 'Crew'], ['Commando', 'Commando']] %>
  </div>
  <div class="field">
    <%= f.radio_button :isLeader, "yes", { checked: true } %> I'm the head cook/PIC! <br>
    <%= f.radio_button :isLeader, "no", { checked: true } %> I'm not a head cook or PIC. <br>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shifts/_shift_pic_confirm_deny.html.erb
<div class='pic_confirm_deny'>
  <div class='title'>Just one more thing...</div>

  <div class='pic_trained'>You've marked that you are PIC trained.</div>
  <div class='question'>Are you the PIC for <%= @shift.niceTitle %>?</div>
  <%= link_to 'No!', add_user_pic_coop_shift_path(@coop, @shift, false), class: 'pic_link pic_false_link' %>
  <%= link_to 'Yes!', add_user_pic_coop_shift_path(@coop, @shift, true), class: 'pic_link pic_true_link' %>
</div>

app/views/shifts/edit.html.erb
<h1>Editing shift</h1>

<%= render 'form' %>

<%= link_to 'Show', @shift %> |
<%= link_to 'Back', shifts_path %>

app/views/shifts/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Listing shifts</h1>

<table>
  <thead>
    <tr>
      <th>Coop</th>
      <th>Day</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Activity</th>
      <th>Leader</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @shifts.each do |shift| %>
      <tr>
        <td><%= Coop.find(shift.coop_id).name %></td>
        <td><%= shift.day %></td>
        <td><%= shift.start_time %></td>
        <td><%= shift.end_time %></td>
        <td><%= shift.activity %></td>
        <% if shift.leader %>
          <td><%= User.find(shift.leader).username %></td>
        <% else %>
          <td>None</td>
        <% end %>
        <td><%= link_to 'Show', shift %></td>
        <% if shift.users.include?(current_user) %>
          <td><%= link_to 'Edit', edit_shift_path(shift) %></td>
          <% if current_user.admin %>
            <td><%= link_to 'Destroy', shift, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
          <td><%= link_to 'Remove from my shifts', remove_user_shift_path(shift) %></td>
        <% else %>
          <td><%= link_to 'Add to my shifts', add_user_shift_path(shift) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shift', new_shift_path %>

app/views/shifts/new.html.erb
<h1>New shift</h1>

<%= render 'form' %>

<%= link_to 'Back', shifts_path %>

app/views/shifts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Coop:</strong>
  <%= Coop.find(@shift.coop_id).name %>
</p>

<p>
  <strong>Day:</strong>
  <%= @shift.day %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @shift.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @shift.end_time %>
</p>

<p>
  <strong>Activity:</strong>
  <%= @shift.activity %>
</p>

<p>
  <!--TODO: privacy -->
  <% if @shift.leader %>
    <strong>Leader:</strong>
    <%= User.find(@shift.leader).username %>
  <% end %>
</p>

<%= link_to 'Edit', edit_shift_path(@shift) %> |
<% if @shift.users.include?(current_user) %>
  <%= link_to 'Remove from my shifts', remove_user_shift_path %> |
<% else %>
  <%= link_to 'Add to my shifts', add_user_shift_path %> |
<% end %>
<%= link_to 'Back', shifts_path %>