config/routes.rb
CoopSite::Application.routes.draw do

  root 'coops#index'

  get "/auth/google_login/callback" => "sessions#create"
  get "/signout" => "sessions#destroy", :as => :signout

  resources :coops do
    resources :meals do
      collection do
        get "edit_mult"
        put "update_mult"
      end
    end

    resources :shifts do
      collection do
        get "edit_mult"
        put "update_mult"
      end

      member do
        get "add_user"
        get "remove_user"
        get "add_user_pic/:pic", action: 'add_user_pic', as: 'add_user_pic'
      end

      resources :swap_requests do
        member do
          get "resolve"
        end
      end
    end

    member do
      get 'generate_member_join_link'
      get 'generate_admin_join_link'
      get 'member_join_link/:member_join_hash', action: 'member_join'
      get 'admin_join_link/:admin_join_hash', action: 'admin_join'
    end
  end

  resources :users do
    get 'edit_shifts'
  end

end

app/models/meal.rb
class Meal < ActiveRecord::Base

  belongs_to :coop
  has_and_belongs_to_many :shifts
  belongs_to :user

  ## meal_info is public
  ## discussion_info is private to members

  include TimeHelper

  def day
    days = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
    days[start_time.to_date.wday]
  end

  def has_public_info?
    self.meal_info.present?
  end

  def has_private_info?
    (self.head_cook || self.user || self.discussion_info.present? || self.meal_info.present?)
  end

  def irreg_time
    field_name = self.meal_type
    if field_name == 'breakfast'
      field_name = 'bfast'
    end
    field_name << '_time'
    calendarTime(self.start_time) != calendarTime(self.coop[field_name])
  end

  def self.delete_all(type, coop)
    default_meals = Meal.where(coop: coop, meal_type: type, name: nil) # nil name implies that it was a regularly sched meal
    default_meals.each do |meal|
      if meal.shifts
        meal.shifts.each do |shift|
          shift.swap_requests.each do |sr|
            sr.destroy
          end
          shift.destroy
        end
      end
      meal.destroy
    end
  end

  def self.makeMeals(type, params, coop)
    end_of_fall = Date.new(Date.today.year, 12, 31)
    end_of_spring = Date.new(Date.today.year, 5, 30)
    days = ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday']
    curdate = Date.today
    curdate < end_of_spring ? end_date = end_of_spring : end_date = end_of_fall
    meals = {}
    shifts = {}
    (0..6).each do |daynum|
      meals[daynum] = []
      shifts[daynum] = []
    end

    while curdate < end_date
      if (params[days[curdate.wday]+'_'+type])
        meal = Meal.update_meal(curdate, params['time'], type, coop)
        meals[curdate.wday] << meal
        shifts[curdate.wday] = meal.shifts
      end
      curdate = curdate.next_day
    end

    (0..6).each do |daynum|
      if meals[daynum].length > 0
        Shift.makeForMealsOnDay(daynum, meals[daynum], params, coop, shifts[daynum])
      else
        Meal.deleteMealsForDay(type, daynum)
      end
    end
  end

  def self.deleteMealsForDay(type, daynum)
    Meal.where(meal_type: type).each do |meal|
      if (meal.start_time.strftime('%w') == daynum.to_s)
        if meal.shifts
          meal.shifts.each do |shift|
            shift.swap_requests.each do |sr|
              sr.destroy
            end
            shift.destroy
          end
        end
        meal.destroy
      end
    end
  end

  def date
    self.start_time.to_date
  end

  def date=(a_date)
    a_date = Date.parse(a_date)
    oldstart = self.start_time || DateTime.now
    oldend = self.end_time || DateTime.now
    self.start_time = DateTime.new(a_date.year, a_date.month, a_date.day, oldstart.hour, oldstart.min)
    self.end_time = DateTime.new(a_date.year, a_date.month, a_date.day, oldend.hour, oldend.min)
  end

  def start_time_no_date
    self.start_time.to_time
  end

  def start_time_no_date=(time)
    unless self.start_time
      self.start_time = DateTime.now
    end
    self.start_time = DateTime.new(self.start_time.year, self.start_time.month, self.start_time.day, time.hour, time.min)
  end

  def end_time_no_date
    self.end_time.to_time
  end

  def end_time_no_date=(time)
    unless self.end_time
      self.end_time = DateTime.now
    end
    self.end_time = DateTime.new(self.end_time.year, self.end_time.month, self.end_time.day, time.hour, time.min)
  end

  def from_params(params)
    new_params = {}
    params.each do | key, value |
      if key.count('(') == 0 && value && value.length > 0
        # has no parens in key name
        new_params[key] = value
      end
    end
    new_params[:start_time_no_date] = Meal.time_from_select(params['start_time_no_date(4i)'], params['start_time_no_date(5i)'])
    new_params
  end

  private

    def self.time_from_select(hours, mins)
      Time.parse("#{hours}:#{mins}").utc
    end

    def self.create_meal(curdate, start_time, meal_type, coop)
      time = DateTime.new(curdate.year, curdate.month, curdate.day, start_time.hour, start_time.min)
      Meal.create start_time: time, meal_type: meal_type, isSpecial: false, end_time: time + Rational(1, 24), coop: coop
    end
    def self.update_meal(curdate, start_time, meal_type, coop)
      time = DateTime.new(curdate.year, curdate.month, curdate.day, start_time.hour, start_time.min)
      old_date_bod = DateTime.new(curdate.year, curdate.month, curdate.day,0,0,0)
      old_date_eod = DateTime.new(curdate.year, curdate.month, curdate.day,23,59,59)
      new_meal = {}
      old_meal = Meal.where(meal_type: meal_type, isSpecial: false, coop: coop, start_time: old_date_bod..old_date_eod).first
      if old_meal
        new_meal = old_meal
        old_meal[:start_time] = time
        old_meal[:end_time] = time + Rational(1, 24)
        old_meal.save
      else
        new_meal = Meal.create start_time: time, meal_type: meal_type, isSpecial: false, end_time: time + Rational(1, 24), coop: coop
      end
      new_meal
    end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  before_action :set_meal, only: [:show, :edit, :update, :destroy]
  before_action :check_for_user, only: [:edit, :update, :destroy, :edit_mult]
  before_action :set_coop, only: [:new, :create, :edit, :edit_mult, :update_mult]
  before_action :is_admin, only: [:edit_mult, :update_mult]
  before_action :set_selected

  include TimeHelper

  # GET /meals
  # GET /meals.json
  def index
    @meals = Meal.all
  end

  # GET /meals/1
  # GET /meals/1.json
  def show
  end

  # GET /meals/new
  def new
    time = DateTime.now.change(min: 0)
    @meal = Meal.new({start_time: time, end_time: time + (60*60)})
  end

  # GET /meals/1/edit
  def edit
  end

  def edit_mult
  end

  def update_mult
    update_hash = @coop.set_meals_shifts(coop_meal_shift_params)
    update_hash.merge!(@coop.set_non_meal_shifts(coop_non_meal_shift_params))
    if @coop.update(update_hash)
      if @coop.update(coop_params)
        if (breakfast_params)
          if breakfast_params == 'delete'
            Meal.delete_all('breakfast', @coop)
            @coop.no_meal('breakfast')
          else
            @breakfasts = Meal.makeMeals('breakfast', breakfast_params, @coop)
          end
        end
        if (lunch_params)
          if lunch_params == 'delete'
            Meal.delete_all('lunch', @coop)
            @coop.no_meal('lunch')
          else
            @lunches = Meal.makeMeals('lunch', lunch_params, @coop)
          end
        end
        if (dinner_params)
          if dinner_params == 'delete'
            Meal.delete_all('dinner', @coop)
            @coop.no_meal('dinner')
          else
            @dinners = Meal.makeMeals('dinner', dinner_params, @coop)
          end
        end
        if (commando_params)
          if commando_params == 'delete'
            Shift.delete_all('commando', @coop)
            @coop.no_shift('commando')
          else
            Shift.make_shifts('commando', commando_params, @coop)
          end
        end
        if (mid_crew_params)
          if mid_crew_params == 'delete'
            Shift.delete_all('mid_crew', @coop)
            @coop.no_shift('mid_crew')
          else
            Shift.make_shifts('mid_crew', mid_crew_params, @coop)
          end
        end
        if (other_shift_params)
          if other_shift_params == 'delete'
            Shift.delete_all('other_shift', @coop)
            @coop.no_shift('other_shift')
          else
            Shift.make_shifts('other_shift', other_shift_params, @coop)
          end
        end

        puts "****** BEFORE SAVE"
        puts @coop.inspect
        if @coop.save
          puts "******* SAVED"
        else
          puts "******** SAVE FAILED"
        end
        puts "****** AFTER SAVE"
        puts @coop.inspect

        redirect_to @coop, notice: 'Successfully added meals and shifts'
      else
        redirect_to edit_coop_path(@coop), notice: 'Failed to update coop'
      end
    else
      redirect_to edit_coop_path(@coop), notice: 'Failed to update coop'
    end
  end

  # POST /meals
  # POST /meals.json
  def create
    @meal = Meal.new
    @meal.update(@meal.from_params(meal_params))
    @meal.coop = @coop
    respond_to do |format|
      if @meal.save
        format.html { redirect_to coop_path(@meal.coop), notice: 'Meal was successfully created.' }
        format.json { render action: 'show', status: :created, location: @meal }
      else
        format.html { render action: 'new' }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meals/1
  # PATCH/PUT /meals/1.json
  def update
    respond_to do |format|
      @meal.user = current_user
      if @meal.update(@meal.from_params(meal_params))
        format.html { redirect_to coop_path(@meal.coop), notice: 'Meal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meals/1
  # DELETE /meals/1.json
  def destroy
    @meal.destroy
    respond_to do |format|
      format.html { redirect_to meals_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meal
      @meal = Meal.find(params[:id])
    end

    def set_coop
      @coop = Coop.find(params[:coop_id]);
    end

    def check_for_user
      unless current_user
        redirect_to @coop, notice: 'Must be signed in to do that'
      end
    end

    def is_admin
      unless current_user.admin?
        redirect_to root_path, notice: 'Must be admin to do that!'
      end
    end

    def breakfast_params
      unless params[:breakfast]
        return 'delete'
      end
      bp = params.permit(:breakfast_hour, :breakfast_min, :breakfast_ampm, :monday_breakfast, :tuesday_breakfast, :wednesday_breakfast, :thursday_breakfast, :friday_breakfast, :saturday_breakfast, :sunday_breakfast, :kp_breakfast, :cook_1_breakfast, :cook_2_breakfast, :pre_crew_breakfast, :crew_breakfast, :custom_shift_1_b, :custom_shift_2_b, :custom_shift_3_b)
      bp['time'] = time_from_select(bp[:breakfast_hour], bp[:breakfast_min], bp[:breakfast_ampm])
      bp
    end

    def lunch_params
      unless params[:lunch]
        return 'delete'
      end
      lp = params.permit(:lunch_hour, :lunch_min, :lunch_ampm, :monday_lunch, :tuesday_lunch, :wednesday_lunch, :thursday_lunch, :friday_lunch, :saturday_lunch, :sunday_lunch, :kp_lunch, :cook_1_lunch, :cook_2_lunch, :pre_crew_lunch, :crew_lunch, :custom_shift_1_l, :custom_shift_2_l, :custom_shift_3_l)
      lp['time'] = time_from_select(lp[:lunch_hour], lp[:lunch_min], lp[:lunch_ampm])
      lp
    end

    def dinner_params
      unless params[:dinner]
        return 'delete'
      end
      dp = params.permit(:dinner_hour, :dinner_min, :dinner_ampm, :monday_dinner, :tuesday_dinner, :wednesday_dinner, :thursday_dinner, :friday_dinner, :saturday_dinner, :sunday_dinner, :kp_dinner, :cook_1_dinner, :cook_2_dinner, :pre_crew_dinner, :crew_dinner, :custom_shift_1_d, :custom_shift_2_d, :custom_shift_3_d)
      dp['time'] = time_from_select(dp[:dinner_hour], dp[:dinner_min], dp[:dinner_ampm])
      dp
    end

    def coop_params
      pcp = params.permit(:member_descrip, :public_descrip, :other_shift_name, :custom_shift_1_l, :custom_shift_2_l, :custom_shift_3_l, :custom_shift_1_b, :custom_shift_2_b, :custom_shift_3_b, :custom_shift_1_d, :custom_shift_2_d, :custom_shift_3_d)
      pcp['bfast_time'] = breakfast_params['time'] if breakfast_params
      pcp['lunch_time'] = lunch_params['time'] if lunch_params
      pcp['dinner_time'] = dinner_params['time'] if dinner_params
      pcp['commando_time'] = commando_params['time'] if commando_params
      pcp['mid_crew_time'] = mid_crew_params['time'] if mid_crew_params
      pcp['other_shift_time'] = other_shift_params['time'] if other_shift_params
      pcp
    end

    def coop_meal_shift_params
      params.permit(:monday_lunch, :tuesday_lunch, :wednesday_lunch, :thursday_lunch, :friday_lunch, :saturday_lunch, :sunday_lunch, :kp_lunch, :cook_1_lunch, :cook_2_lunch, :pre_crew_lunch, :crew_lunch, :monday_breakfast, :tuesday_breakfast, :wednesday_breakfast, :thursday_breakfast, :friday_breakfast, :saturday_breakfast, :sunday_breakfast, :kp_breakfast, :cook_1_breakfast, :cook_2_breakfast, :pre_crew_breakfast, :crew_breakfast, :monday_dinner, :tuesday_dinner, :wednesday_dinner, :thursday_dinner, :friday_dinner, :saturday_dinner, :sunday_dinner, :kp_dinner, :cook_1_dinner, :cook_2_dinner, :pre_crew_dinner, :crew_dinner)
    end

    def coop_non_meal_shift_params
      params.permit(:monday_commando, :tuesday_commando, :wednesday_commando, :thursday_commando, :friday_commando, :saturday_commando, :sunday_commando, :monday_mid_crew, :tuesday_mid_crew, :wednesday_mid_crew, :thursday_mid_crew, :friday_mid_crew, :saturday_mid_crew, :sunday_mid_crew, :monday_other_shift, :tuesday_other_shift, :wednesday_other_shift, :thursday_other_shift, :friday_other_shift, :saturday_other_shift, :sunday_other_shift)
    end

    def commando_params
      unless params[:commando]
        return 'delete'
      end
      commando = params.permit(:commando_hour, :commando_min, :commando_ampm, :monday_commando, :tuesday_commando, :wednesday_commando, :thursday_commando, :friday_commando, :saturday_commando, :sunday_commando)
      commando['time'] = time_from_select(commando[:commando_hour], commando[:commando_min], commando[:commando_ampm])
      commando
    end

    def mid_crew_params
      unless params[:mid_crew]
        return 'delete'
      end
      mid_crew = params.permit(:mid_crew_hour, :mid_crew_min, :mid_crew_ampm, :monday_mid_crew, :tuesday_mid_crew, :wednesday_mid_crew, :thursday_mid_crew, :friday_mid_crew, :saturday_mid_crew, :sunday_mid_crew)
      mid_crew['time'] = time_from_select(mid_crew[:mid_crew_hour], mid_crew[:mid_crew_min], mid_crew[:mid_crew_ampm])
      mid_crew
    end

    def other_shift_params
      unless params[:other_shift]
        return 'delete'
      end
      other_shift = params.permit(:other_shift_name, :other_shift_hour, :other_shift_min, :other_shift_ampm, :monday_other_shift, :tuesday_other_shift, :wednesday_other_shift, :thursday_other_shift, :friday_other_shift, :saturday_other_shift, :sunday_other_shift)
      other_shift['time'] = time_from_select(other_shift[:other_shift_hour], other_shift[:other_shift_min], other_shift[:other_shift_ampm])
      other_shift
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meal_params
      params.require(:meal).permit(:meal_type, :isSpecial, :name, :cancelled, :discussion_info, :meal_info, :end_time_no_date, :start_time_no_date, :date)
    end

    def set_selected
      @selected = 'calendar'
    end
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/views/meals/_form.html.erb
<%= form_for [@coop, @meal] do |f| %>
  <% if @meal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meal.errors.count, "error") %> prohibited this meal from being saved:</h2>

      <ul>
      <% @meal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field cancelled">
    <%= f.check_box :cancelled %>
    <span class='label'>Cancel this meal</span>
  </div>

  <div class='upper_row'>

  <div class="field meal_name">
    <span class='label'>Meal Title:</span>
    <%= f.text_field :name %>
  </div>

  <div class="field start_time">
    <span class='label'>Start Time:</span>
    <%= f.time_select :start_time_no_date, {ampm: true, minute_step: 5, ignore_date: true} %>
  </div>
  </div>

  <div class='lower_row'>
  <div class="field meal_info">
    <span class='label'>Information to display publicly about this meal:</span>
    <%= f.text_area :meal_info %>
  </div>
  <div class="field discussion_info">
    <span class='label'>Information to display only to <%= @coop.name %> members about this meal:</span>
    <%= f.text_area :discussion_info %>
  </div>
  </div>

  <div class="actions">
    <%= f.submit 'Save' %>
  </div>
<% end %>

app/views/meals/_table_show.html.erb
<% if meal.cancelled %>
  <div class='cancelled'>
    <span class='cancel_text'>CANCELLED</span>
    <% if @user && @user.coop == @coop %>
    <%= link_to 'edit', edit_coop_meal_path(@coop, meal), class: 'meal_edit_link' %>
      <div class='mouseover'>
        <% if @private_info %>
          <% if meal.head_cook %>
            <h3>Head Cook:</h3>
            <p><%= User.find(meal.head_cook).username %></p>
          <% end %>
          <% if meal.meal_info.present? %>
            <h3>Public Info</h3>
            <p><%= meal.meal_info %></p>
          <% end %>
          <% if meal.discussion_info.present? %>
            <h3>Member Info</h3>
            <p><%= meal.discussion_info %></p>
          <% end %>
          <% if meal.user %>
            <h3>Last Edited By:</h3>
            <p><%= meal.user.username %></p>
          <% end %>
      <% else %>
        <% if meal.meal_info.present? %>
            <h3>Meal Info</h3>
            <p><%= meal.meal_info %></p>
        <% end %>
      <% end %>
      </div>
    <% end %>
  </div>
<% else %>
<% if meal == @next_meal %>
  <div class='next_meal'>
<% else %>
  <div class='a_meal'>
<% end %>
  <div class='meal_info_holder'>
    <div class='namearea'>
      <% if meal.name %>
      <span class='name'><%= meal.name %></span>
      <% else %>
      <span class='type'><%= "#{meal.day} #{meal.meal_type}" %></span>
      <% end %>
    </div>
    <% if meal.irreg_time %>
    <div class='time'>
      <%= calendarTime(meal.start_time) %>
    </div>
    <% end %>
      <% if (@private_info && meal.has_private_info?) || ((!@private_info) && meal.has_public_info?) %>
        <div class='more_info'>click for more info</div>
      <% end %>
    </div>
      <div class='mouseover'>
        <% if @private_info %>
          <% if meal.head_cook %>
            <h3>Head Cook:</h3>
            <p><%= User.find(meal.head_cook).username %></p>
          <% end %>
          <% if meal.meal_info.present? %>
            <h3>Public Info</h3>
            <p><%= meal.meal_info %></p>
          <% end %>
          <% if meal.discussion_info.present? %>
            <h3>Member Info</h3>
            <p><%= meal.discussion_info %></p>
          <% end %>
          <% if meal.user %>
            <h3>Last Edited By:</h3>
            <p><%= meal.user.username %></p>
          <% end %>
      <% else %>
        <% if meal.meal_info.present? %>
            <h3>Meal Info</h3>
            <p><%= meal.meal_info %></p>
        <% end %>
      <% end %>
    </div>
    <% if @user && @user.coop == @coop %>
    <%= link_to 'edit', edit_coop_meal_path(@coop, meal), class: 'meal_edit_link' %>
    <% end %>
  </div>
<% end %>

app/views/meals/edit.html.erb
<div class='meal_edit_page'>
<div class='meal_header'>
  <%= @meal.day %> <%= @meal.meal_type.capitalize %> <%= @meal.start_time.strftime("%m/%-d/%Y") %>
</div>
<%= render 'form' %>
</div>

app/views/meals/edit_mult.html.erb
<div class='edit_coop_page'>

<p id="notice"><%= notice %></p>

<h2 class='edit_welcome'>You're editing your co-op's information! You can find this page anytime by clicking the "edit co-op information" link on your co-op's calendar page.</h2>
<%= render 'mult_meal_form' %>

</div>

app/views/meals/index.html.erb
<h1>Listing meals</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Isspecial</th>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @meals.each do |meal| %>
      <tr>
        <td><%= meal.type %></td>
        <td><%= meal.isSpecial %></td>
        <td><%= meal.name %></td>
        <td><%= link_to 'Show', meal %></td>
        <td><%= link_to 'Edit', edit_meal_path(meal) %></td>
        <td><%= link_to 'Destroy', meal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meal', new_meal_path %>

app/views/meals/new.html.erb
<h1>New meal</h1>

<%= render 'form' %>

<%= link_to 'Back', coop_path(@coop) %>

app/views/meals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @meal.type %>
</p>

<p>
  <strong>Isspecial:</strong>
  <%= @meal.isSpecial %>
</p>

<p>
  <strong>Name:</strong>
  <%= @meal.name %>
</p>

<%= link_to 'Edit', edit_meal_path(@meal) %> |
<%= link_to 'Back', meals_path %>