config/routes.rb
CoopSite::Application.routes.draw do

  root 'coops#index'

  get "/auth/google_login/callback" => "sessions#create"
  get "/signout" => "sessions#destroy", :as => :signout

  resources :coops do
    resources :meals do
      collection do
        get "edit_mult"
        put "update_mult"
      end
    end

    resources :shifts do
      collection do
        get "edit_mult"
        put "update_mult"
      end

      member do
        get "add_user"
        get "remove_user"
        get "add_user_pic/:pic", action: 'add_user_pic', as: 'add_user_pic'
      end

      resources :swap_requests do
        member do
          get "resolve"
        end
      end
    end

    member do
      get 'generate_member_join_link'
      get 'generate_admin_join_link'
      get 'member_join_link/:member_join_hash', action: 'member_join'
      get 'admin_join_link/:admin_join_hash', action: 'admin_join'
    end
  end

  resources :users do
    get 'edit_shifts'
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <% if @coop %>
    <title><%= @coop.name.upcase %> CO-OP</title>
  <% else %>
    <title>CO-OPERATION NATION</title>
  <% end %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class='header'>
  <% unless @hide_nav_links %>

    <div class="nav_bar">
      <ul id='site_nav'>

        <% if current_user %>
          <li><%= link_to 'Meals Calendar', coop_path(current_user.coop), class: (@selected == 'calendar') ? 'selected tab' : 'tab' %></li>
          <li><%= link_to 'Shifts Hub', user_path(current_user), class: (@selected == 'shifts') ? 'selected tab' : 'tab' %></li>
        <% end %>

        <li>
          <%# link_to 'Other co-ops', root_path, class: 'tab' %>
          <a href="#">Co-ops &#x25BC;</a>
          <ul>
            <% @coops.each do |coop| %>
              <li><%= link_to coop.name, coop %></li>
            <% end %>
          </ul>
        </li>

        <% if current_user %>
          <!-- Account drop-down -->
          <li>
            <a href="#">My Account &#x25BC;</a>
            <ul>
              <li><%= link_to 'Settings', edit_user_path(current_user), class: (@selected == 'edit_user') ? 'selected tab' : 'tab', id: "account_dropdown" %></li>
              <li><%= link_to 'Sign out', signout_path, class: 'tab' %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Sign in', "/auth/google_login", class: 'tab' %></li>
        <% end %>
      </ul>
    </div>

  <% end %>

  <% if @coop %>
    <div class='title'><%= @coop.name.upcase %> CO-OP</div>
  <% else %>
    <div class='title'>CO-OPERATION NATION</div>
  <% end %>

</div>

<div class='main_content_area'>
<%= yield %>
</div>

<div class='footer'>
  <span>Have questions, comments, concerns? Send feedback to obradradish@gmail.com!</span>
</div>
</body>
</html>